/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal.ProtexView;

import Principal.DAO.DespezaDAO;
import Principal.DTO.DespezaDTO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author Gabriel
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) JTDespezas.getModel();
        JTDespezas.setRowSorter(new TableRowSorter(modelo));
        PesquisarTable();
    }

    public void PesquisarTable(){
        DefaultTableModel modelo = (DefaultTableModel) JTDespezas.getModel();
        modelo.setNumRows(0);
        DespezaDAO ddao = new DespezaDAO();
        
        for(DespezaDTO d: ddao.Pesquisar()){
            
            modelo.addRow(new Object[]{
                d.getId(),               
                d.getDespeza(),
                d.getDescricao(),
                d.getValorGasto()
            });
        }
    }
    
    public void PesquisarTableDesc(String desc){
        DefaultTableModel modelo = (DefaultTableModel) JTDespezas.getModel();
        modelo.setNumRows(0);
        DespezaDAO ddao = new DespezaDAO();
        
        for(DespezaDTO d: ddao.PesquisarDesc(desc)){
            
            modelo.addRow(new Object[]{
                d.getId(),
                d.getDespeza(),
                d.getDescricao(),
                d.getValorGasto()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrolPanel = new javax.swing.JScrollPane();
        JTDespezas = new javax.swing.JTable();
        btnCalcular = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        txtDespeza = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        txtValorGasto = new javax.swing.JTextField();
        txtBuscaDesc = new javax.swing.JTextField();
        txtValorTotal = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        Painel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Protex | Principal");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScrolPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ScrolPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        ScrolPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ScrolPanel.setInheritsPopupMenu(true);
        ScrolPanel.setMinimumSize(new java.awt.Dimension(1, 16));

        JTDespezas.setAutoCreateRowSorter(true);
        JTDespezas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Despeza", "Descrição", "Valor Gasto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTDespezas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        JTDespezas.setFocusable(false);
        JTDespezas.setRowHeight(40);
        JTDespezas.setSelectionBackground(new java.awt.Color(190, 190, 190));
        JTDespezas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTDespezasMouseClicked(evt);
            }
        });
        JTDespezas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTDespezasKeyReleased(evt);
            }
        });
        ScrolPanel.setViewportView(JTDespezas);

        getContentPane().add(ScrolPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 640, 190));

        btnCalcular.setContentAreaFilled(false);
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 265, 110, 33));

        btnLimpar.setContentAreaFilled(false);
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 267, 100, 30));

        btnPesquisar.setContentAreaFilled(false);
        btnPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 100, 30));

        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 100, 30));

        btnEditar.setContentAreaFilled(false);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 100, 30));

        btnDeletar.setContentAreaFilled(false);
        btnDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 197, 104, 30));

        txtDespeza.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        getContentPane().add(txtDespeza, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 130, 200, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtDescricao.setColumns(20);
        txtDescricao.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 160, 200, 45));

        txtValorGasto.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtValorGasto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorGastoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorGastoKeyTyped(evt);
            }
        });
        getContentPane().add(txtValorGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 128, 170, -1));

        txtBuscaDesc.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        getContentPane().add(txtBuscaDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 180, 30));

        txtValorTotal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtValorTotal.setEnabled(false);
        getContentPane().add(txtValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 230, 200, -1));
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 190, 20));

        Painel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Images/Tela_Principal1.png"))); // NOI18N
        getContentPane().add(Painel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtDespeza.setText("");
        txtValorGasto.setText("");
        txtDescricao.setText("");
        txtValorTotal.setText("");
        txtBuscaDesc.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
            
        DespezaDTO objDespeza = new DespezaDTO();
        
        
        objDespeza.setDespeza(txtDespeza.getText());
        
       double valorGasto = Double.parseDouble(txtValorGasto.getText());
       java.text.NumberFormat nf = java.text.NumberFormat.getNumberInstance();
       nf.setMinimumFractionDigits(2);
       nf.setMaximumFractionDigits(2);
       String str = nf.format(valorGasto);
       str = str.replaceAll(",",".");
       objDespeza.setValorGasto(Double.parseDouble(str));
        
        objDespeza.setDescricao(txtDescricao.getText());
        
        DespezaDAO objDespezaDAO = new DespezaDAO();
        
        
        boolean cad = objDespezaDAO.registrar(objDespeza);
        if(cad){
            JOptionPane.showMessageDialog(null, "Despeza cadastrada com sucesso!");
            
            txtDespeza.setText("");
            txtDescricao.setText("");
            txtValorGasto.setText("");
            PesquisarTable();
        } else {
            JOptionPane.showMessageDialog(null, "Falha ao cadastrar despeza");
        }
       
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
           if (JTDespezas.getSelectedRow() !=-1){
            
                DespezaDTO objDespeza = new DespezaDTO();
                objDespeza.setDespeza(txtDespeza.getText());

                double valorGasto = Double.parseDouble(txtValorGasto.getText());
                java.text.NumberFormat nf = java.text.NumberFormat.getNumberInstance();
                nf.setMinimumFractionDigits(2);
                nf.setMaximumFractionDigits(2);
                String str = nf.format(valorGasto);
                str = str.replaceAll(",",".");
                objDespeza.setValorGasto(Double.parseDouble(str));

                objDespeza.setDescricao(txtDescricao.getText());
                objDespeza.setId((int)JTDespezas.getValueAt(JTDespezas.getSelectedRow(), 0));

                DespezaDAO objDespezaDAO = new DespezaDAO();
                boolean cad = objDespezaDAO.editar(objDespeza);
                if(cad){
                    JOptionPane.showMessageDialog(null, "Despeza editada com sucesso!");
                    txtDespeza.setText("");
                    txtDescricao.setText("");
                    txtValorGasto.setText("");
                    PesquisarTable();
                } else {
                    JOptionPane.showMessageDialog(null, "Falha ao editar despeza");
                }
               
        } 
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        if(txtBuscaDesc.getText().isEmpty()){
            PesquisarTable();
        } else{
            PesquisarTableDesc(txtBuscaDesc.getText());
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void JTDespezasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTDespezasMouseClicked
        if (JTDespezas.getSelectedRow() !=-1){
            
            txtDespeza.setText(JTDespezas.getValueAt(JTDespezas.getSelectedRow(), 1).toString());
            txtDescricao.setText(JTDespezas.getValueAt(JTDespezas.getSelectedRow(), 2).toString());
            txtValorGasto.setText(JTDespezas.getValueAt(JTDespezas.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_JTDespezasMouseClicked

    private void JTDespezasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTDespezasKeyReleased
        if (JTDespezas.getSelectedRow() !=-1){
            
            txtDespeza.setText(JTDespezas.getValueAt(JTDespezas.getSelectedRow(), 1).toString());
            txtDescricao.setText(JTDespezas.getValueAt(JTDespezas.getSelectedRow(), 2).toString());
            txtValorGasto.setText(JTDespezas.getValueAt(JTDespezas.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_JTDespezasKeyReleased

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        DespezaDTO objDespeza = new DespezaDTO();
        
        
        DespezaDAO objDespezaDAO = new DespezaDAO();
                boolean cad = objDespezaDAO.calcular(objDespeza);
                if(cad){
                    txtValorTotal.setText(String.valueOf(objDespeza.getValorTotal()));

                } else {
                    JOptionPane.showMessageDialog(null, "Falha ao calcular despezas");
                }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        if (JTDespezas.getSelectedRow() !=-1){
            
                DespezaDTO objDespeza = new DespezaDTO();
                objDespeza.setId((int)JTDespezas.getValueAt(JTDespezas.getSelectedRow(), 0));

                DespezaDAO objDespezaDAO = new DespezaDAO();
                boolean cad = objDespezaDAO.deletar(objDespeza);
                if(cad){
                    JOptionPane.showMessageDialog(null, "Despeza deletada com sucesso!");
                    PesquisarTable();
                    txtDespeza.setText("");
                    txtDescricao.setText("");
                    txtValorGasto.setText("");

                } else {
                    JOptionPane.showMessageDialog(null, "Falha ao deletar despeza");
                }
               
        } 
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void txtValorGastoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorGastoKeyTyped

    }//GEN-LAST:event_txtValorGastoKeyTyped

    private void txtValorGastoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorGastoKeyReleased
        txtValorGasto.setText(txtValorGasto.getText().replaceAll("[^0-9 | ^.]", ""));
    }//GEN-LAST:event_txtValorGastoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTDespezas;
    private javax.swing.JLabel Painel;
    private javax.swing.JScrollPane ScrolPanel;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtBuscaDesc;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtDespeza;
    private javax.swing.JTextField txtValorGasto;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
