/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal.ProtexView;

import Principal.DAO.CadastroDAO;
import Principal.DTO.LoginDTO;
import Principal.Validacao.Numero;
import javax.swing.JOptionPane;
import Jm.JMascara;
/**
 *
 * @author Gabriel
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnCadastrar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        txtDocumento = new javax.swing.JTextField();
        radioCPF = new javax.swing.JRadioButton();
        radioCNPJ = new javax.swing.JRadioButton();
        Painel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Protex | Cadastro");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastrar.setContentAreaFilled(false);
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 372, 100, 30));

        txtNome.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 178, 230, 24));

        txtEmail.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 202, 230, 24));

        txtTelefone.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        txtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefoneKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefoneKeyTyped(evt);
            }
        });
        getContentPane().add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 226, 230, 24));

        txtEndereco.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        getContentPane().add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 230, 24));

        txtLogin.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 278, 230, 24));

        txtSenha.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 307, 230, 24));

        txtDocumento.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        txtDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDocumentoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDocumentoKeyTyped(evt);
            }
        });
        getContentPane().add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 336, 230, 24));

        buttonGroup1.add(radioCPF);
        getContentPane().add(radioCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 369, -1, -1));

        buttonGroup1.add(radioCNPJ);
        getContentPane().add(radioCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 369, -1, -1));

        Painel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        Painel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Images/Tela_Cadastro1.png"))); // NOI18N
        getContentPane().add(Painel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneKeyTyped
        Numero.justNumbers(evt);
    }//GEN-LAST:event_txtTelefoneKeyTyped

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        
        if(txtEmail.getText().isEmpty() || txtTelefone.getText().isEmpty() || txtEndereco.getText().isEmpty() || txtLogin.getText().isEmpty() || txtSenha.getText().isEmpty() || txtDocumento.getText().isEmpty()){
              JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!");
          } else if(!radioCPF.isSelected() && !radioCNPJ.isSelected()){
              JOptionPane.showMessageDialog(null, "Selecione um Documento");
          } else if(radioCNPJ.isSelected() && txtDocumento.getText().length()!=18 ){
              JOptionPane.showMessageDialog(null, "CNPJ Invalido");
          } else if(radioCPF.isSelected() && txtDocumento.getText().length()!=14){
              JOptionPane.showMessageDialog(null, "CPF Invalido");
          } else if(txtTelefone.getText().length()>18){
              JOptionPane.showMessageDialog(null, "Telefone Invalido");
          } else{   
                    
                    LoginDTO c = new LoginDTO();
                    
              
                    c.setNome(txtNome.getText());
                    c.setEmail(txtEmail.getText());
                    c.setTelefone(txtTelefone.getText());
                    c.setEndereco(txtEndereco.getText());
                    c.setLogin(txtLogin.getText());
                    c.setSenha(txtSenha.getText());
                    c.setDocumento(txtDocumento.getText());
                    c.setIdCadastro(c.getIdCadastro());
                    
                    
                    if(radioCPF.isSelected()){
                    c.setTipoDocumento("CPF");
                    } else if(radioCNPJ.isSelected()){
                    c.setTipoDocumento("CNPJ");
                    }
                    
                    CadastroDAO objCadastroDAO = new CadastroDAO();
                
                    boolean cad = objCadastroDAO.cadastrar(c);
                    if(cad){
                        JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
                        TelaLogin telaDeLogin = new TelaLogin();
                        telaDeLogin.setVisible(true);
                        this.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "Falha ao cadastrar");
                    }
          } 
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumentoKeyTyped
        Numero.justNumbers(evt);
    }//GEN-LAST:event_txtDocumentoKeyTyped

    private void txtTelefoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneKeyReleased
        txtTelefone.setText(JMascara.GetJmascaraFone(txtTelefone.getText()));
    }//GEN-LAST:event_txtTelefoneKeyReleased

    private void txtDocumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumentoKeyReleased
        txtDocumento.setText(JMascara.GetJmascaraCpfCnpj(txtDocumento.getText()));
    }//GEN-LAST:event_txtDocumentoKeyReleased
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Painel;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton radioCNPJ;
    private javax.swing.JRadioButton radioCPF;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
